### ISSUE TITLE
Pull Payment Payout does not send when using LNbank wallet for store

### ISSUE THREAD

**Issue by merklemonk** [dennisreimann/btcpayserver#17]
**Plugin**
LNbank v1.2.1

**Describe the bug**
A Pull Payment Payout does not send if a store is using a LNbank wallet with a sufficient balance.
  
**To Reproduce the bug**
Steps to reproduce the reported bug:

1. create a store
2. create a lnbank wallet
3. use lnbank wallet for store in lightning settings `~/stores/{storeId}/lightning/BTC/setup`
4. fund lnbank wallet with sats
5. create pull payment for store with minimum expiration time to 1 day and with amount less than lnbank wallet balance 
6. enter a bolt11 invoice with expiry greater than 1 day in the pull-payment destination field
7. approve and send payment (Error): 

```
System.FormatException: LNURL uses bech32 and 'lnurl' as the hrp (LUD1) or an lnurl LUD17 scheme. 
   at LNURL.LNURL.Parse(String lnurl, String& tag)
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.Process(ISupportedPaymentMethod paymentMethod, PayoutData[] payouts)
```
this the reference to the `LNURL.Parse()` FormatException: [LNURL.cs](https://github.com/Kukks/LNURL/blob/d83470f7b793fcdd36711d3cdfb45e28c60d4e14/LNURL/LNURL.cs#L37-L59)

https://github.com/dennisreimann/btcpayserver/blob/e7180ac82a61c7f4d2cf3287fa91c70c612a70db/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs#L116-L123

If I have a bolt11 invoice, this case is not hit and will first try `case LNURLPayClaimDestinaton lnurlPayClaimDestinaton:` where it fails on `LNURL.Parse()`

**Expected behavior**

When using `Internal Node` I can successfully payout an invoice.

**Other Variables**

LNURL Enabled/Disabled: I've tried creating new pull-payments after enabling and after disabling LNURL.

Setting Payout Processor: I've tried creating pull-payments with and without Payout Processor `~/stores/{storeId}/payout-processors/lightning-automated/BTC` . Maybe the behavior changes when payout is processed with [UILightningLikePayoutController.cs](https://github.com/dennisreimann/btcpayserver/blob/plugins/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs#L207) vs [LightningAutomatedPayoutProcessor.cs](https://github.com/dennisreimann/btcpayserver/blob/plugins/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs#L83) ?

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    BTCPay Server v1.5.2.0 (Altcoins)
- Plugin Name and Version:  LNbank v1.2.1
- Deployment Method: Docker
- Browser: Firefox

**Comment by dennisreimann** [comment]
This will be fixed with the upcoming version. Unfortunately it will also take a BTCPay Server update, that's why it is taking a bit longer. Thanks for reporting and sorry for the hassle!

**Comment by dennisreimann** [comment]
This is fixed with BTCPay v1.6.0 and LNbank v1.2.3 — thanks for reporting!
